#ifndef __PMIC_WRAP_SSPM_REGS_H__
#define __PMIC_WRAP_SSPM_REGS_H__

#define PMIC_WRAP_SSPM_BASE (0x10848000)

#define PMIC_WRAP_SSPM_WACS_SSPM_EN          ((UINT32P)(PMIC_WRAP_SSPM_BASE+0x200))
#define PMIC_WRAP_SSPM_INIT_DONE_SSPM        ((UINT32P)(PMIC_WRAP_SSPM_BASE+0x204))
#define PMIC_WRAP_SSPM_WACS_SSPM_CMD         ((UINT32P)(PMIC_WRAP_SSPM_BASE+0x208))
#define PMIC_WRAP_SSPM_WACS_SSPM_RDATA       ((UINT32P)(PMIC_WRAP_SSPM_BASE+0x20C))
#define PMIC_WRAP_SSPM_WACS_SSPM_VLDCLR      ((UINT32P)(PMIC_WRAP_SSPM_BASE+0x210))
#define PMIC_WRAP_SSPM_SSPM_STA              ((UINT32P)(PMIC_WRAP_SSPM_BASE+0x33C))

#endif //__PMIC_WRAP_SSPM_REGS_H__

