# input:
# TARGET_PREBUILT_PRELOADER
# PL_MODE
# CFG_PRELOADER_EXTENSION

ifneq (,$(PL_MODE))
  PRELOADER_OUT := $(TARGET_OUT_INTERMEDIATES)/PRELOADER_$(PL_MODE)_OBJ
  INSTALLED_PRELOADER_TARGET := $(PRODUCT_OUT)/preloader_$(PRELOADER_TARGET_PRODUCT)_$(PL_MODE).bin
  PREBUILT_PRELOADER_TARGET := $(TARGET_PREBUILT_PRELOADER_$(PL_MODE))
  PRELOADER_BIN := $(PRODUCT_OUT)/preloader_$(PL_MODE).bin
  TARGET_PRELOADER := $(PRODUCT_OUT)/preloader_$(PL_MODE).img
  MTK_OTA_PREPROCESS_EXTRA_IMAGES := $(MTK_OTA_PREPROCESS_EXTRA_IMAGES) $(notdir $(TARGET_PRELOADER))
  BOARD_PACK_RADIOIMAGES := $(BOARD_PACK_RADIOIMAGES) $(notdir $(TARGET_PRELOADER))
  INSTALLED_RADIOIMAGE_TARGET := $(INSTALLED_RADIOIMAGE_TARGET) $(TARGET_PRELOADER)
  ifeq ($(CFG_PRELOADER_EXTENSION), 1)
    INSTALLED_LOADER_EXT_TARGET := $(PRODUCT_OUT)/loader_ext_$(PL_MODE).img
    SIGN_LOADER_EXT_TARGET := $(addsuffix -verified$(suffix $(INSTALLED_LOADER_EXT_TARGET)),$(basename $(INSTALLED_LOADER_EXT_TARGET)))
  endif
else
  PRELOADER_OUT := $(TARGET_OUT_INTERMEDIATES)/PRELOADER_OBJ
  INSTALLED_PRELOADER_TARGET := $(PRODUCT_OUT)/preloader_$(PRELOADER_TARGET_PRODUCT).bin
  PREBUILT_PRELOADER_TARGET := $(TARGET_PREBUILT_PRELOADER)
  PRELOADER_BIN := $(PRODUCT_OUT)/preloader.bin
  TARGET_PRELOADER := $(PRODUCT_OUT)/preloader.img
  MTK_OTA_PREPROCESS_EXTRA_IMAGES := $(MTK_OTA_PREPROCESS_EXTRA_IMAGES) $(notdir $(TARGET_PRELOADER))
  BOARD_PACK_RADIOIMAGES := $(BOARD_PACK_RADIOIMAGES) $(notdir $(TARGET_PRELOADER))
  INSTALLED_RADIOIMAGE_TARGET := $(INSTALLED_RADIOIMAGE_TARGET) $(TARGET_PRELOADER) $(INSTALLED_PRELOADER_TARGET)
  ifeq ($(CFG_PRELOADER_EXTENSION), 1)
    INSTALLED_LOADER_EXT_TARGET := $(PRODUCT_OUT)/loader_ext.img
    SIGN_LOADER_EXT_TARGET := $(addsuffix -verified$(suffix $(INSTALLED_LOADER_EXT_TARGET)),$(basename $(INSTALLED_LOADER_EXT_TARGET)))
  endif
endif

ifneq ($(wildcard $(PREBUILT_PRELOADER_TARGET)),)

$(INSTALLED_PRELOADER_TARGET): $(PREBUILT_PRELOADER_TARGET)
	$(hide) mkdir -p $(dir $@)
	$(hide) cp -f $< $@

$(PRELOADER_BIN): $(INSTALLED_PRELOADER_TARGET)
	$(hide) mkdir -p $(dir $@)
	$(hide) cp -f $< $@

$(TARGET_PRELOADER): $(dir $(PREBUILT_PRELOADER_TARGET))$(notdir $(TARGET_PRELOADER))
	$(hide) mkdir -p $(dir $@)
	$(hide) cp -f $< $@

ifeq ($(CFG_PRELOADER_EXTENSION), 1)
$(INSTALLED_LOADER_EXT_TARGET): $(dir $(PREBUILT_PRELOADER_TARGET))$(notdir $(INSTALLED_LOADER_EXT_TARGET))
	$(hide) mkdir -p $(dir $@)
	$(hide) cp -f $< $@
endif

preloader pl: $(INSTALLED_PRELOADER_TARGET) $(TARGET_PRELOADER) $(PRELOADER_BIN)
ifeq ($(CFG_PRELOADER_EXTENSION), 1)
preloader pl: $(INSTALLED_LOADER_EXT_TARGET) $(SIGN_LOADER_EXT_TARGET)
endif
$(SIGN_LOADER_EXT_TARGET):

endif#PREBUILT_PRELOADER_TARGET
