HW_INIT_ONLY :=
CFG_BOOT_ARGUMENT :=1
CFG_BATTERY_DETECT :=0
CFG_EMERGENCY_DL_SUPPORT :=0
CFG_RAM_CONSOLE :=0
CFG_UART_TOOL_HANDSHAKE :=0
CFG_USB_TOOL_HANDSHAKE :=0
CFG_USB_DOWNLOAD :=1
CFG_PMT_SUPPORT :=0

CFG_LOAD_SLT_MD_RAMDISK :=1
CFG_LOAD_SLT_MD_DSP :=1
CFG_LOAD_SLT_MD :=1
CFG_LOAD_SLT_SCP :=1
CFG_LOAD_SLT_MD32 :=1
CFG_LOAD_SLT_SSPM :=1
CFG_LOAD_AP_ROM :=1
CFG_LOAD_UBOOT :=0
CFG_LOAD_MD_ROM :=1

CFG_LOAD_CONN_SYS :=0
CFG_APWDT_DISABLE :=1
CFG_ATF_SUPPORT :=0

MTK_SECURITY_SW_SUPPORT=no
