/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein is
 * confidential and proprietary to MediaTek Inc. and/or its licensors. Without
 * the prior written permission of MediaTek inc. and/or its licensors, any
 * reproduction, modification, use or disclosure of MediaTek Software, and
 * information contained herein, in whole or in part, shall be strictly
 * prohibited.
 * 
 * MediaTek Inc. (C) 2010. All rights reserved.
 * 
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER
 * ON AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR
 * NONINFRINGEMENT. NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH
 * RESPECT TO THE SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY,
 * INCORPORATED IN, OR SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES
 * TO LOOK ONLY TO SUCH THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO.
 * RECEIVER EXPRESSLY ACKNOWLEDGES THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO
 * OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES CONTAINED IN MEDIATEK
 * SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE
 * RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S
 * ENTIRE AND CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE
 * RELEASED HEREUNDER WILL BE, AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE
 * MEDIATEK SOFTWARE AT ISSUE, OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE
 * CHARGE PAID BY RECEIVER TO MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek
 * Software") have been modified by MediaTek Inc. All revisions are subject to
 * any receiver's applicable license agreements with MediaTek Inc.
 */

#ifndef PLL_H
#define PLL_H

#define APMIXED_BASE		(0x1000C000)
#define CKSYS_BASE		(0x10000000)
#ifndef INFRACFG_AO_BASE
#define INFRACFG_AO_BASE	(0x10001000)
#endif
#ifndef PERICFG_BASE
#define PERICFG_BASE		(0x10003000)
#endif
#define AUDIO_BASE		(0x11220000)
#define MFGCFG_BASE		(0x13000000)
#define MMSYS_CONFIG_BASE	(0x14000000)
#define IMGSYS_BASE		(0x15020000)
#define VENC_GCON_BASE		(0x17000000)
#define CAMSYS_BASE		(0x1A000000)
#define MCUCFG_BASE		(0x0C530000)
#define GCE_BASE		(0x10238000)


/* MCUCFG Register */
#define CPU_PLLDIV_CFG0		(MCUCFG_BASE + 0xA2A0)
#define CPU_PLLDIV_CFG1		(MCUCFG_BASE + 0xA2A4)
#define CPU_PLLDIV_CFG2		(MCUCFG_BASE + 0xA2A8)
#define BUS_PLLDIV_CFG		(MCUCFG_BASE + 0xA2E0)


/* APMIXEDSYS Register */
#define AP_PLL_CON0		(APMIXED_BASE + 0x00)
#define AP_PLL_CON1		(APMIXED_BASE + 0x04)
#define AP_PLL_CON2		(APMIXED_BASE + 0x08)
#define AP_PLL_CON3		(APMIXED_BASE + 0x0C)
#define AP_PLL_CON4		(APMIXED_BASE + 0x10)
#define AP_PLL_CON5		(APMIXED_BASE + 0x14)

#define PLL_PWR_CON0		(APMIXED_BASE + 0x1C)
#define PLL_PWR_CON1		(APMIXED_BASE + 0x20)
#define PLL_ISO_CON0		(APMIXED_BASE + 0x24)
#define PLL_ISO_CON1		(APMIXED_BASE + 0x28)

#define APLL1_TUNER_CON0	(APMIXED_BASE + 0x40)
#define PLLON_CON0		(APMIXED_BASE + 0x44)
#define PLLON_CON1		(APMIXED_BASE + 0x48)

#define ARMPLL_CON0		(APMIXED_BASE + 0x208)
#define ARMPLL_CON1		(APMIXED_BASE + 0x20C)
#define ARMPLL_CON2		(APMIXED_BASE + 0x210)
#define ARMPLL_CON3		(APMIXED_BASE + 0x214)

#define ARMPLL_L_CON0		(APMIXED_BASE + 0x218)
#define ARMPLL_L_CON1		(APMIXED_BASE + 0x21C)
#define ARMPLL_L_CON2		(APMIXED_BASE + 0x220)
#define ARMPLL_L_CON3		(APMIXED_BASE + 0x224)

#define CCIPLL_CON0		(APMIXED_BASE + 0x228)
#define CCIPLL_CON1		(APMIXED_BASE + 0x22C)
#define CCIPLL_CON2		(APMIXED_BASE + 0x230)
#define CCIPLL_CON3		(APMIXED_BASE + 0x234)

#define UNIVPLL_CON0		(APMIXED_BASE + 0x238)
#define UNIVPLL_CON1		(APMIXED_BASE + 0x23C)
#define UNIVPLL_CON2		(APMIXED_BASE + 0x240)
#define UNIVPLL_CON3		(APMIXED_BASE + 0x244)

#define MFGPLL_CON0		(APMIXED_BASE + 0x248)
#define MFGPLL_CON1		(APMIXED_BASE + 0x24C)
#define MFGPLL_CON2		(APMIXED_BASE + 0x250)
#define MFGPLL_CON3		(APMIXED_BASE + 0x254)

#define MAINPLL_CON0		(APMIXED_BASE + 0x258)
#define MAINPLL_CON1		(APMIXED_BASE + 0x25C)
#define MAINPLL_CON2		(APMIXED_BASE + 0x260)
#define MAINPLL_CON3		(APMIXED_BASE + 0x264)

#define MMPLL_CON0		(APMIXED_BASE + 0x31C)
#define MMPLL_CON1		(APMIXED_BASE + 0x320)
#define MMPLL_CON2		(APMIXED_BASE + 0x324)
#define MMPLL_CON3		(APMIXED_BASE + 0x328)

#define MPLL_CON0		(APMIXED_BASE + 0x32C)
#define MPLL_CON1		(APMIXED_BASE + 0x330)
#define MPLL_CON2		(APMIXED_BASE + 0x334)
#define MPLL_CON3		(APMIXED_BASE + 0x338)

#define MSDCPLL_CON0		(APMIXED_BASE + 0x33C)
#define MSDCPLL_CON1		(APMIXED_BASE + 0x340)
#define MSDCPLL_CON2		(APMIXED_BASE + 0x344)
#define MSDCPLL_CON3		(APMIXED_BASE + 0x348)

#define APLL1_CON0		(APMIXED_BASE + 0x308)
#define APLL1_CON1		(APMIXED_BASE + 0x30C)
#define APLL1_CON2		(APMIXED_BASE + 0x310)
#define APLL1_CON3		(APMIXED_BASE + 0x314)
#define APLL1_CON4		(APMIXED_BASE + 0x318)


/* TOPCKGEN Register */
#define CLK_MODE		(CKSYS_BASE + 0x000)
#define CLK_CFG_UPDATE		(CKSYS_BASE + 0x004)
#define CLK_CFG_0		(CKSYS_BASE + 0x040)
#define CLK_CFG_0_SET		(CKSYS_BASE + 0x044)
#define CLK_CFG_0_CLR		(CKSYS_BASE + 0x048)
#define CLK_CFG_1		(CKSYS_BASE + 0x050)
#define CLK_CFG_1_SET		(CKSYS_BASE + 0x054)
#define CLK_CFG_1_CLR		(CKSYS_BASE + 0x058)
#define CLK_CFG_2		(CKSYS_BASE + 0x060)
#define CLK_CFG_2_SET		(CKSYS_BASE + 0x064)
#define CLK_CFG_2_CLR		(CKSYS_BASE + 0x068)
#define CLK_CFG_3		(CKSYS_BASE + 0x070)
#define CLK_CFG_3_SET		(CKSYS_BASE + 0x074)
#define CLK_CFG_3_CLR		(CKSYS_BASE + 0x078)
#define CLK_CFG_4		(CKSYS_BASE + 0x080)
#define CLK_CFG_4_SET		(CKSYS_BASE + 0x084)
#define CLK_CFG_4_CLR		(CKSYS_BASE + 0x088)
#define CLK_CFG_5		(CKSYS_BASE + 0x090)
#define CLK_CFG_5_SET		(CKSYS_BASE + 0x094)
#define CLK_CFG_5_CLR		(CKSYS_BASE + 0x098)
#define CLK_CFG_6		(CKSYS_BASE + 0x0A0)
#define CLK_CFG_6_SET		(CKSYS_BASE + 0x0A4)
#define CLK_CFG_6_CLR		(CKSYS_BASE + 0x0A8)
#define CLK_CFG_7		(CKSYS_BASE + 0x0B0)
#define CLK_CFG_7_SET		(CKSYS_BASE + 0x0B4)
#define CLK_CFG_7_CLR		(CKSYS_BASE + 0x0B8)
#define CLK_CFG_8		(CKSYS_BASE + 0x0C0)
#define CLK_CFG_8_SET		(CKSYS_BASE + 0x0C4)
#define CLK_CFG_8_CLR		(CKSYS_BASE + 0x0C8)


#define CLK_MISC_CFG_0		(CKSYS_BASE + 0x104)
#define CLK_MISC_CFG_1		(CKSYS_BASE + 0x108)
#define CLK_DBG_CFG		(CKSYS_BASE + 0x10C)
#define CLK_SCP_CFG_0		(CKSYS_BASE + 0x200)
#define CLK_SCP_CFG_1		(CKSYS_BASE + 0x204)
#define CLK26CALI_0		(CKSYS_BASE + 0x220)
#define CLK26CALI_1		(CKSYS_BASE + 0x224)

/* INFRASYS Register */
#define INFRA_BUS_DCM_CTRL			(INFRACFG_AO_BASE + 0x70)
#define PERI_BUS_DCM_CTRL			(INFRACFG_AO_BASE + 0x74)
#define MODULE_SW_CG_0_SET			(INFRACFG_AO_BASE + 0x80)
#define MODULE_SW_CG_0_CLR			(INFRACFG_AO_BASE + 0x84)
#define MODULE_SW_CG_1_SET			(INFRACFG_AO_BASE + 0x88)
#define MODULE_SW_CG_1_CLR			(INFRACFG_AO_BASE + 0x8C)
#define MODULE_SW_CG_0_STA			(INFRACFG_AO_BASE + 0x90)
#define MODULE_SW_CG_1_STA			(INFRACFG_AO_BASE + 0x94)
#define MODULE_SW_CG_2_SET			(INFRACFG_AO_BASE + 0xA4)
#define MODULE_SW_CG_2_CLR			(INFRACFG_AO_BASE + 0xA8)
#define MODULE_SW_CG_2_STA			(INFRACFG_AO_BASE + 0xAC)
#define MODULE_SW_CG_3_SET			(INFRACFG_AO_BASE + 0xC0)
#define MODULE_SW_CG_3_CLR			(INFRACFG_AO_BASE + 0xC4)
#define MODULE_SW_CG_3_STA			(INFRACFG_AO_BASE + 0xC8)
#define INFRA_TOPAXI_SI0_CTL			(INFRACFG_AO_BASE + 0x0200)
#define INFRA_TOPAXI_PROTECTEN			(INFRACFG_AO_BASE + 0x0220)
#define INFRA_TOPAXI_PROTECTEN_STA1		(INFRACFG_AO_BASE + 0x0228)
#define INFRA_TOPAXI_PROTECTEN_1		(INFRACFG_AO_BASE + 0x0250)
#define INFRA_TOPAXI_PROTECTEN_STA1_1		(INFRACFG_AO_BASE + 0x0258)
#define INFRA_TOPAXI_PROTECTEN_SET		(INFRACFG_AO_BASE + 0x02A0)
#define INFRA_TOPAXI_PROTECTEN_CLR		(INFRACFG_AO_BASE + 0x02A4)
#define INFRA_TOPAXI_PROTECTEN_1_SET		(INFRACFG_AO_BASE + 0x02A8)
#define INFRA_TOPAXI_PROTECTEN_1_CLR		(INFRACFG_AO_BASE + 0x02AC)

/* MMSYS */
#define MMSYS_CG_CLR0            (MMSYS_CONFIG_BASE + 0x108)


#endif
