###################################################################
# flag
###################################################################

MOD_SRC  =
MOD_OBJ  = $(PRELOADER_OUT)/obj

###################################################################
# source files
# - add your file here !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
###################################################################

MOD_SRC :=
MOD_SRC += ufs_aio_core.c
MOD_SRC += ufs_aio_error.c
MOD_SRC += ufs_aio_hcd.c
MOD_SRC += ufs_aio_interface.c
MOD_SRC += ufs_aio_quirks.c
MOD_SRC += ufs_aio_rpmb.c
MOD_SRC += ufs_aio_utils.c

###################################################################
# target
###################################################################

include $(COMMON_FILE_MK)

