/*
 * Generated by MTK SP Drv_CodeGen Version 03.13.6 for MT6580. Copyright MediaTek Inc. (C) 2013.
 * Mon Feb 26 21:57:48 2024
 * Do Not Modify the File.
 */

#ifndef __CUST_AUXADC_TOOL_H
#define __CUST_AUXADC_TOOL_H


#define AUXADC_TEMPERATURE_CHANNEL     0
#define AUXADC_TEMPERATURE1_CHANNEL     1


#endif //_CUST_AUXADC_TOOL_H


